### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/ngx-launcher#259]
https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-frontend/issues/4565/

```
TypeError: Cannot read property 'indexOf' of undefined
  at validateRepo (~/ngx-forge/src/app/launcher/step-indicator/step-indicator.component.js:72:1)
  at t.validateProjectName (~/ngx-forge/src/app/launcher/step-indicator/step-indicator.component.js:108:1)
  at handleEvent (~/@angular/core/@angular/core.es5.js:11998:86)
  at handleEvent (~/@angular/core/@angular/core.es5.js:12717:68)
  at dispatchEvent (~/@angular/core/@angular/core.es5.js:8614:1)
...
(8 additional frame(s) were not displayed)
```

**Comment by gastaldi** [comment]
Seems to be resolved. Closing
